# Generated by Django 5.2.7 on 2025-10-14 05:57

import django.contrib.auth.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kullanici',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ad', models.CharField(max_length=100)),
                ('soyad', models.CharField(max_length=100)),
                ('e_posta', models.EmailField(max_length=150, unique=True)),
                ('sifre_hash', models.CharField(max_length=255)),
                ('telefon', models.CharField(blank=True, max_length=20, null=True)),
                ('kayit_tarihi', models.DateTimeField(auto_now_add=True)),
                ('aktif_mi', models.BooleanField(default=True)),
                ('son_giris_tarihi', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Kullanıcı',
                'verbose_name_plural': 'Kullanıcılar',
                'db_table': 'kullanicilar',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rol_adi', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roller',
                'db_table': 'roller',
            },
        ),
        migrations.CreateModel(
            name='UzmanlikAlani',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('alan_adi', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Uzmanlık Alanı',
                'verbose_name_plural': 'Uzmanlık Alanları',
                'db_table': 'uzmanlikalanlari',
            },
        ),
        migrations.CreateModel(
            name='Diyetisyen',
            fields=[
                ('kullanici', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('universite', models.CharField(blank=True, max_length=200, null=True)),
                ('hakkinda_bilgi', models.TextField(blank=True, null=True)),
                ('profil_fotografi_url', models.CharField(blank=True, max_length=255, null=True)),
                ('hizmet_ucreti', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
            options={
                'verbose_name': 'Diyetisyen',
                'verbose_name_plural': 'Diyetisyenler',
                'db_table': 'diyetisyenler',
            },
        ),
        migrations.CreateModel(
            name='Bildirim',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('mesaj', models.TextField()),
                ('tur', models.CharField(blank=True, max_length=50, null=True)),
                ('okundu_mu', models.BooleanField(default=False)),
                ('tarih', models.DateTimeField(auto_now_add=True)),
                ('alici_kullanici', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bildirim',
                'verbose_name_plural': 'Bildirimler',
                'db_table': 'bildirimler',
            },
        ),
        migrations.CreateModel(
            name='DanisanSaglikVerisi',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('boy', models.SmallIntegerField(blank=True, null=True)),
                ('kilo', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('hedef_kilo', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('alerjiler', models.TextField(blank=True, null=True)),
                ('kronik_hastaliklar', models.TextField(blank=True, null=True)),
                ('son_guncelleme', models.DateTimeField(auto_now=True)),
                ('danisan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Danışan Sağlık Verisi',
                'verbose_name_plural': 'Danışan Sağlık Verileri',
                'db_table': 'danisansaglikverileri',
            },
        ),
        migrations.CreateModel(
            name='Makale',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('baslik', models.CharField(max_length=255)),
                ('ozet', models.TextField(blank=True, null=True)),
                ('icerik', models.TextField()),
                ('yayimlanma_tarihi', models.DateTimeField(blank=True, null=True)),
                ('onay_durumu', models.CharField(choices=[('BEKLEMEDE', 'Beklemede'), ('ONAYLANDI', 'Onaylandı'), ('REDDEDILDI', 'Reddedildi')], default='BEKLEMEDE', max_length=20)),
                ('yazar_kullanici', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Makale',
                'verbose_name_plural': 'Makaleler',
                'db_table': 'makaleler',
            },
        ),
        migrations.CreateModel(
            name='Randevu',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('randevu_tarih_saat', models.DateTimeField()),
                ('kamera_linki', models.CharField(blank=True, max_length=255, null=True)),
                ('durum', models.CharField(choices=[('BEKLEMEDE', 'Beklemede'), ('ONAYLANDI', 'Onaylandı'), ('TAMAMLANDI', 'Tamamlandı'), ('IPTAL_EDILDI', 'İptal Edildi')], max_length=50)),
                ('tip', models.CharField(choices=[('ON_GORUSME', 'Ön Görüşme'), ('UCRETLI', 'Ücretli')], max_length=20)),
                ('ucret_tutar', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('baslangic_saati_gercek', models.DateTimeField(blank=True, null=True)),
                ('bitis_saati_gercek', models.DateTimeField(blank=True, null=True)),
                ('iptal_eden_tur', models.CharField(blank=True, choices=[('DIYETISYEN', 'Diyetisyen'), ('DANISAN', 'Danışan'), ('ADMIN', 'Admin'), ('SISTEM', 'Sistem')], max_length=20, null=True)),
                ('iptal_edilme_tarihi', models.DateTimeField(blank=True, null=True)),
                ('iptal_nedeni', models.TextField(blank=True, null=True)),
                ('admin_inceleme_gerekiyor', models.BooleanField(default=False)),
                ('danisan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('diyetisyen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.diyetisyen')),
            ],
            options={
                'verbose_name': 'Randevu',
                'verbose_name_plural': 'Randevular',
                'db_table': 'randevular',
            },
        ),
        migrations.AddField(
            model_name='kullanici',
            name='rol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kullanicilar', to='core.rol'),
        ),
        migrations.CreateModel(
            name='Yorum',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('puan', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('yorum_metni', models.TextField(blank=True, null=True)),
                ('yorum_tarihi', models.DateTimeField(auto_now_add=True)),
                ('onay_durumu', models.CharField(choices=[('BEKLEMEDE', 'Beklemede'), ('ONAYLANDI', 'Onaylandı'), ('REDDEDILDI', 'Reddedildi')], default='BEKLEMEDE', max_length=20)),
                ('danisan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('diyetisyen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.diyetisyen')),
            ],
            options={
                'verbose_name': 'Yorum',
                'verbose_name_plural': 'Yorumlar',
                'db_table': 'yorumlar',
            },
        ),
        migrations.CreateModel(
            name='DiyetListesi',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('baslik', models.CharField(max_length=255)),
                ('icerik', models.TextField()),
                ('yuklenme_tarihi', models.DateTimeField(auto_now_add=True)),
                ('danisan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('randevu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.randevu')),
                ('diyetisyen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.diyetisyen')),
            ],
            options={
                'verbose_name': 'Diyet Listesi',
                'verbose_name_plural': 'Diyet Listeleri',
                'db_table': 'diyetlisteleri',
            },
        ),
        migrations.CreateModel(
            name='Musaitlik',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('gun', models.SmallIntegerField(choices=[(1, 'Pazartesi'), (2, 'Salı'), (3, 'Çarşamba'), (4, 'Perşembe'), (5, 'Cuma'), (6, 'Cumartesi'), (7, 'Pazar')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)])),
                ('baslangic_saati', models.TimeField()),
                ('bitis_saati', models.TimeField()),
                ('diyetisyen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.diyetisyen')),
            ],
            options={
                'verbose_name': 'Müsaitlik',
                'verbose_name_plural': 'Müsaitlikler',
                'db_table': 'musaitlikler',
                'unique_together': {('diyetisyen', 'gun', 'baslangic_saati', 'bitis_saati')},
            },
        ),
        migrations.CreateModel(
            name='DiyetisyenUzmanlikAlani',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uzmanlik_alani', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.uzmanlikalani')),
                ('diyetisyen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.diyetisyen')),
            ],
            options={
                'verbose_name': 'Diyetisyen Uzmanlık Alanı',
                'verbose_name_plural': 'Diyetisyen Uzmanlık Alanları',
                'db_table': 'diyetisyenuzmanlikalanlari',
                'unique_together': {('diyetisyen', 'uzmanlik_alani')},
            },
        ),
        migrations.CreateModel(
            name='DanisanDiyetisyenEslesme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('on_gorusme_yapildi_mi', models.BooleanField(default=False)),
                ('hasta_mi', models.BooleanField(default=False)),
                ('eslesme_tarihi', models.DateTimeField(auto_now_add=True)),
                ('danisan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('diyetisyen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.diyetisyen')),
            ],
            options={
                'verbose_name': 'Danışan-Diyetisyen Eşleşme',
                'verbose_name_plural': 'Danışan-Diyetisyen Eşleşmeleri',
                'db_table': 'danisandiyetisyeneslesme',
                'unique_together': {('diyetisyen', 'danisan')},
            },
        ),
    ]
