# Generated by Django 5.2.7 on 2025-10-14 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='kullanici',
            managers=[
            ],
        ),
    ]
