# Generated by Django 5.2.7 on 2025-10-14 06:05

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_kullanici_managers'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromosyonKodu',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('kod', models.CharField(max_length=50, unique=True)),
                ('indirim_miktari', models.DecimalField(decimal_places=2, max_digits=5)),
                ('indirim_tipi', models.CharField(choices=[('YUZDE', 'Yüzde'), ('SABIT', 'Sabit')], max_length=20)),
                ('kullanim_limiti', models.IntegerField(default=1)),
                ('kullanim_sayisi', models.IntegerField(default=0)),
                ('gecerlilik_tarihi', models.DateTimeField(blank=True, null=True)),
                ('aktif_mi', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Promosyon Kodu',
                'verbose_name_plural': 'Promosyon Kodları',
                'db_table': 'promosyonkodlari',
            },
        ),
        migrations.CreateModel(
            name='SistemAyari',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ayar_adi', models.CharField(max_length=100, unique=True)),
                ('ayar_degeri', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Sistem Ayarı',
                'verbose_name_plural': 'Sistem Ayarları',
                'db_table': 'sistemayarlari',
            },
        ),
        migrations.CreateModel(
            name='Soru',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('soru_metni', models.TextField()),
                ('soru_tipi', models.CharField(choices=[('SINGLE_CHOICE', 'Tek Seçim'), ('MULTI_CHOICE', 'Çoklu Seçim'), ('TEXT', 'Metin'), ('NUMBER', 'Sayı'), ('DATE', 'Tarih')], max_length=20)),
                ('sira', models.IntegerField(default=0)),
                ('gerekli', models.BooleanField(default=False)),
                ('min_deger', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('max_deger', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('min_tarih', models.DateField(blank=True, null=True)),
                ('max_tarih', models.DateField(blank=True, null=True)),
                ('placeholder', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'Soru',
                'verbose_name_plural': 'Sorular',
                'db_table': 'sorular',
            },
        ),
        migrations.CreateModel(
            name='AcilIletisim',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('talep_tarihi_saati', models.DateTimeField(auto_now_add=True)),
                ('telegram_bildirim_gonderildi_mi', models.BooleanField(default=False)),
                ('cozum_durumu', models.CharField(default='BEKLEMEDE', max_length=50)),
                ('talep_eden_kullanici', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Acil İletişim',
                'verbose_name_plural': 'Acil İletişimler',
                'db_table': 'acililetisim',
            },
        ),
        migrations.CreateModel(
            name='AdminYonlendirme',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('neden', models.TextField(blank=True, null=True)),
                ('durum', models.CharField(choices=[('GERCEKLESTI', 'Gerçekleşti'), ('BEKLEMEDE', 'Beklemede'), ('REDDEDILDI', 'Reddedildi')], default='GERCEKLESTI', max_length=20)),
                ('olusturma_tarihi', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='admin_yonlendirmeleri', to=settings.AUTH_USER_MODEL)),
                ('danisan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yonlendirilen_danisan', to=settings.AUTH_USER_MODEL)),
                ('hedef_diyetisyen', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='hedef_yonlendirmeler', to='core.diyetisyen')),
                ('ilgili_randevu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.randevu')),
                ('kaynak_diyetisyen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kaynak_yonlendirmeler', to='core.diyetisyen')),
            ],
            options={
                'verbose_name': 'Admin Yönlendirme',
                'verbose_name_plural': 'Admin Yönlendirmeleri',
                'db_table': 'adminyonlendirmeleri',
            },
        ),
        migrations.CreateModel(
            name='AnalitikVeri',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('olay_adi', models.CharField(max_length=100)),
                ('sayfa_url', models.TextField(blank=True, null=True)),
                ('oturum_tarihi', models.DateTimeField(auto_now_add=True)),
                ('kullanici', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Analitik Veri',
                'verbose_name_plural': 'Analitik Verileri',
                'db_table': 'analitikveri',
            },
        ),
        migrations.CreateModel(
            name='AnketOturum',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('durum', models.CharField(choices=[('ACIK', 'Açık'), ('TAMAMLANDI', 'Tamamlandı')], default='ACIK', max_length=20)),
                ('baslama_tarihi', models.DateTimeField(auto_now_add=True)),
                ('tamamlama_tarihi', models.DateTimeField(blank=True, null=True)),
                ('kullanici', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Anket Oturum',
                'verbose_name_plural': 'Anket Oturumları',
                'db_table': 'anketoturumlari',
            },
        ),
        migrations.CreateModel(
            name='BasariHikayesi',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('baslangic_kilo', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('bitis_kilo', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('hikaye_metni', models.TextField()),
                ('fotograflar', models.JSONField(blank=True, null=True)),
                ('yayim_onayi', models.BooleanField(default=False)),
                ('danisan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('diyetisyen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.diyetisyen')),
            ],
            options={
                'verbose_name': 'Başarı Hikayesi',
                'verbose_name_plural': 'Başarı Hikayeleri',
                'db_table': 'basarihikayeleri',
            },
        ),
        migrations.CreateModel(
            name='DiyetisyenNot',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('baslik', models.CharField(blank=True, max_length=200, null=True)),
                ('not_metin', models.TextField()),
                ('sadece_diyetisyen_gorsun', models.BooleanField(default=True)),
                ('olusma_tarihi', models.DateTimeField(auto_now_add=True)),
                ('guncelleme_tarihi', models.DateTimeField(blank=True, null=True)),
                ('silindi', models.BooleanField(default=False)),
                ('danisan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diyetisyen_notlari', to=settings.AUTH_USER_MODEL)),
                ('diyetisyen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.diyetisyen')),
                ('olusturan', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='olusturulan_notlar', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Diyetisyen Not',
                'verbose_name_plural': 'Diyetisyen Notları',
                'db_table': 'diyetisyennotlari',
            },
        ),
        migrations.CreateModel(
            name='DiyetisyenOdeme',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('donem_baslangic', models.DateTimeField()),
                ('donem_bitis', models.DateTimeField()),
                ('odenecek_net_tutar', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('odeme_durumu', models.CharField(default='BEKLEMEDE', max_length=50)),
                ('odeme_tarihi', models.DateTimeField(blank=True, null=True)),
                ('diyetisyen', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.diyetisyen')),
            ],
            options={
                'verbose_name': 'Diyetisyen Ödeme',
                'verbose_name_plural': 'Diyetisyen Ödemeleri',
                'db_table': 'diyetisyenodemeleri',
            },
        ),
        migrations.CreateModel(
            name='Dosya',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('baglanti_tipi', models.CharField(choices=[('KULLANICI', 'Kullanıcı'), ('RANDEVU', 'Randevu'), ('DIYETISYEN_NOTU', 'Diyetisyen Notu'), ('DANISAN_SAGLIK', 'Danışan Sağlık'), ('MAKALE', 'Makale'), ('BASARI_HIKAYESI', 'Başarı Hikayesi')], max_length=30)),
                ('baglanti_id', models.BigIntegerField()),
                ('dosya_adi', models.CharField(max_length=255)),
                ('uzanti', models.CharField(blank=True, max_length=20, null=True)),
                ('mime_type', models.CharField(blank=True, max_length=100, null=True)),
                ('boyut_byte', models.BigIntegerField(blank=True, null=True)),
                ('saklama_yolu', models.TextField()),
                ('dosya_turu', models.CharField(choices=[('FOTOGRAF', 'Fotoğraf'), ('BELGE', 'Belge'), ('DIGER', 'Diğer')], max_length=20)),
                ('aciklama', models.TextField(blank=True, null=True)),
                ('gizlilik', models.CharField(choices=[('OZEL', 'Özel'), ('DANISAN_GOREBILIR', 'Danışan Görebilir'), ('DIYETISYEN_GOREBILIR', 'Diyetisyen Görebilir'), ('ADMIN', 'Admin'), ('HERKESE_ACIK', 'Herkese Açık')], default='OZEL', max_length=20)),
                ('olusturma_tarihi', models.DateTimeField(auto_now_add=True)),
                ('yukleyen_kullanici', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dosya',
                'verbose_name_plural': 'Dosyalar',
                'db_table': 'dosyalar',
            },
        ),
        migrations.CreateModel(
            name='MakaleYorum',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('yorum_metni', models.TextField()),
                ('yorum_tarihi', models.DateTimeField(auto_now_add=True)),
                ('kullanici', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('makale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.makale')),
            ],
            options={
                'verbose_name': 'Makale Yorum',
                'verbose_name_plural': 'Makale Yorumları',
                'db_table': 'makaleyorumlari',
            },
        ),
        migrations.CreateModel(
            name='OdemeHareketi',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('toplam_ucret', models.DecimalField(decimal_places=2, max_digits=10)),
                ('komisyon_orani', models.DecimalField(decimal_places=2, max_digits=4)),
                ('komisyon_miktari', models.DecimalField(decimal_places=2, max_digits=10)),
                ('diyetisyen_kazanci', models.DecimalField(decimal_places=2, max_digits=10)),
                ('odeme_tarihi', models.DateTimeField(auto_now_add=True)),
                ('odeme_durumu', models.CharField(max_length=50)),
                ('danisan', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='odeme_hareketleri_danisan', to=settings.AUTH_USER_MODEL)),
                ('diyetisyen', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.diyetisyen')),
                ('randevu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.randevu')),
            ],
            options={
                'verbose_name': 'Ödeme Hareketi',
                'verbose_name_plural': 'Ödeme Hareketleri',
                'db_table': 'odemehareketleri',
            },
        ),
        migrations.CreateModel(
            name='PlatformGeriBildirim',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('puan', models.SmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('konu', models.CharField(blank=True, max_length=100, null=True)),
                ('metin', models.TextField()),
                ('tarih', models.DateTimeField(auto_now_add=True)),
                ('kullanici', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Platform Geri Bildirim',
                'verbose_name_plural': 'Platform Geri Bildirimleri',
                'db_table': 'platformgeribildirimleri',
            },
        ),
        migrations.CreateModel(
            name='RandevuMudahaleTalebi',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('olusturan_tur', models.CharField(choices=[('OTOMATIK', 'Otomatik'), ('ADMIN', 'Admin'), ('SISTEM', 'Sistem')], default='OTOMATIK', max_length=20)),
                ('durum', models.CharField(choices=[('ACIK', 'Açık'), ('COZUMLENDI', 'Çözümlendi')], default='ACIK', max_length=20)),
                ('aciklama', models.TextField(blank=True, null=True)),
                ('olusma_tarihi', models.DateTimeField(auto_now_add=True)),
                ('kapama_tarihi', models.DateTimeField(blank=True, null=True)),
                ('yapilan_islem', models.TextField(blank=True, null=True)),
                ('kapatan_admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('randevu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.randevu')),
            ],
            options={
                'verbose_name': 'Randevu Müdahale Talebi',
                'verbose_name_plural': 'Randevu Müdahale Talepleri',
                'db_table': 'randevumudahaletalebi',
            },
        ),
        migrations.CreateModel(
            name='Referans',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('taniklik_metni', models.TextField()),
                ('onay_durumu', models.CharField(choices=[('BEKLEMEDE', 'Beklemede'), ('ONAYLANDI', 'Onaylandı'), ('REDDEDILDI', 'Reddedildi')], default='BEKLEMEDE', max_length=20)),
                ('yayimlanma_tarihi', models.DateTimeField(blank=True, null=True)),
                ('danisan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Referans',
                'verbose_name_plural': 'Referanslar',
                'db_table': 'referanslar',
            },
        ),
        migrations.CreateModel(
            name='Sikayet',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sikayet_tipi', models.CharField(blank=True, max_length=50, null=True)),
                ('sikayet_metni', models.TextField()),
                ('sikayet_tarihi', models.DateTimeField(auto_now_add=True)),
                ('cozum_durumu', models.CharField(default='ACIK', max_length=50)),
                ('randevu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.randevu')),
                ('sikayet_eden', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='sikayet_edenler', to=settings.AUTH_USER_MODEL)),
                ('sikayet_edilen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sikayet_edilenler', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Şikayet',
                'verbose_name_plural': 'Şikayetler',
                'db_table': 'sikayetler',
            },
        ),
        migrations.CreateModel(
            name='SoruSecenek',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('etiket', models.CharField(max_length=200)),
                ('deger', models.CharField(max_length=100)),
                ('sira', models.IntegerField(default=0)),
                ('soru', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.soru')),
            ],
            options={
                'verbose_name': 'Soru Seçenek',
                'verbose_name_plural': 'Soru Seçenekleri',
                'db_table': 'sorusecenekleri',
                'unique_together': {('soru', 'deger')},
            },
        ),
        migrations.CreateModel(
            name='AnketCevap',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cevap_metin', models.TextField(blank=True, null=True)),
                ('cevap_sayi', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cevap_tarih', models.DateField(blank=True, null=True)),
                ('anket_oturum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.anketoturum')),
                ('soru', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.soru')),
                ('cevap_secenek', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.sorusecenek')),
            ],
            options={
                'verbose_name': 'Anket Cevap',
                'verbose_name_plural': 'Anket Cevapları',
                'db_table': 'anketcevaplari',
                'unique_together': {('anket_oturum', 'soru')},
            },
        ),
        migrations.CreateModel(
            name='SoruSeti',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ad', models.CharField(max_length=150)),
                ('aciklama', models.TextField(blank=True, null=True)),
                ('aktif_mi', models.BooleanField(default=True)),
                ('olusturma_tarihi', models.DateTimeField(auto_now_add=True)),
                ('hedef_rol', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.rol')),
            ],
            options={
                'verbose_name': 'Soru Seti',
                'verbose_name_plural': 'Soru Setleri',
                'db_table': 'sorusetleri',
            },
        ),
        migrations.AddField(
            model_name='soru',
            name='soru_seti',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.soruseti'),
        ),
        migrations.AddField(
            model_name='anketoturum',
            name='soru_seti',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.soruseti'),
        ),
        migrations.CreateModel(
            name='AnketCokluSecim',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('anket_cevap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.anketcevap')),
                ('secenek', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.sorusecenek')),
            ],
            options={
                'verbose_name': 'Anket Çoklu Seçim',
                'verbose_name_plural': 'Anket Çoklu Seçimler',
                'db_table': 'anketcoklusecimler',
                'unique_together': {('anket_cevap', 'secenek')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='anketoturum',
            unique_together={('kullanici', 'soru_seti')},
        ),
    ]
