# Generated by Django 4.2.25 on 2025-10-14 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_promosyonkodu_sistemayari_soru_acililetisim_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='diyetisyen',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True),
        ),
    ]
