# Generated by Django 4.2.25 on 2025-10-14 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_diyetisyen_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diyetisyen',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
