# Generated by Django 5.2.5 on 2025-10-14 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_diyetisyen_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kullanici',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='kullanici',
            name='sifre_hash',
        ),
    ]
