# Generated by Django 5.2.5 on 2025-10-14 12:17

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_kullanici_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='musaitlik',
            name='aktif',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='musaitlik',
            name='olusturma_tarihi',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dosya',
            name='gizlilik',
            field=models.CharField(choices=[('OZEL', 'Özel'), ('DANISAN_GOREBILIR', 'Danışan Görebilir'), ('DIYETISYEN_GOREBILIR', 'Diyetisyen Görebilir'), ('admin', 'admin'), ('HERKESE_ACIK', 'Herkese Açık')], default='OZEL', max_length=20),
        ),
        migrations.AlterField(
            model_name='musaitlik',
            name='diyetisyen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='musaitlikler', to='core.diyetisyen'),
        ),
        migrations.AlterField(
            model_name='randevu',
            name='iptal_eden_tur',
            field=models.CharField(blank=True, choices=[('diyetisyen', 'Diyetisyen'), ('danisan', 'Danışan'), ('admin', 'admin'), ('SISTEM', 'Sistem')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='randevumudahaletalebi',
            name='olusturan_tur',
            field=models.CharField(choices=[('OTOMATIK', 'Otomatik'), ('admin', 'admin'), ('SISTEM', 'Sistem')], default='OTOMATIK', max_length=20),
        ),
        migrations.CreateModel(
            name='DiyetisyenIzin',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('baslangic_tarihi', models.DateField()),
                ('bitis_tarihi', models.DateField()),
                ('izin_tipi', models.CharField(choices=[('TAM_GUN', 'Tam Gün'), ('YARIM_GUN', 'Yarım Gün'), ('SAATLIK', 'Saatlik')], default='TAM_GUN', max_length=20)),
                ('baslangic_saati', models.TimeField(blank=True, null=True)),
                ('bitis_saati', models.TimeField(blank=True, null=True)),
                ('aciklama', models.TextField(blank=True, null=True)),
                ('olusturma_tarihi', models.DateTimeField(auto_now_add=True)),
                ('diyetisyen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='izinler', to='core.diyetisyen')),
            ],
            options={
                'verbose_name': 'Diyetisyen İzin',
                'verbose_name_plural': 'Diyetisyen İzinleri',
                'db_table': 'diyetisyen_izinleri',
            },
        ),
        migrations.CreateModel(
            name='DiyetisyenMusaitlikSablon',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('gun', models.SmallIntegerField(choices=[(1, 'Pazartesi'), (2, 'Salı'), (3, 'Çarşamba'), (4, 'Perşembe'), (5, 'Cuma'), (6, 'Cumartesi'), (7, 'Pazar')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)])),
                ('baslangic_saati', models.TimeField()),
                ('bitis_saati', models.TimeField()),
                ('aktif', models.BooleanField(default=True)),
                ('olusturma_tarihi', models.DateTimeField(auto_now_add=True)),
                ('guncelleme_tarihi', models.DateTimeField(auto_now=True)),
                ('diyetisyen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='musaitlik_sablonlari', to='core.diyetisyen')),
            ],
            options={
                'verbose_name': 'Diyetisyen Müsaitlik Şablonu',
                'verbose_name_plural': 'Diyetisyen Müsaitlik Şablonları',
                'db_table': 'diyetisyen_musaitlik_sablonlari',
                'unique_together': {('diyetisyen', 'gun', 'baslangic_saati', 'bitis_saati')},
            },
        ),
    ]
