# Generated by Django 5.2.5 on 2025-10-14 13:27

import datetime
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0007_musaitlik_aktif_musaitlik_olusturma_tarihi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kullanici',
            name='ad',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='kullanici',
            name='aktif_mi',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='kullanici',
            name='e_posta',
            field=models.EmailField(db_index=True, max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='kullanici',
            name='kayit_tarihi',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='kullanici',
            name='soyad',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='odemehareketi',
            name='danisan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='odeme_hareketleri_danisan', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='odemehareketi',
            name='diyetisyen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.diyetisyen'),
        ),
        migrations.AlterField(
            model_name='odemehareketi',
            name='diyetisyen_kazanci',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='odemehareketi',
            name='komisyon_miktari',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='odemehareketi',
            name='komisyon_orani',
            field=models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='odemehareketi',
            name='odeme_durumu',
            field=models.CharField(choices=[('BEKLEMEDE', 'Beklemede'), ('TAMAMLANDI', 'Tamamlandı'), ('IPTAL_EDILDI', 'İptal Edildi'), ('IADE_EDILDI', 'İade Edildi')], db_index=True, default='BEKLEMEDE', max_length=50),
        ),
        migrations.AlterField(
            model_name='odemehareketi',
            name='odeme_tarihi',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='odemehareketi',
            name='randevu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.randevu'),
        ),
        migrations.AlterField(
            model_name='odemehareketi',
            name='toplam_ucret',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='randevu',
            name='admin_inceleme_gerekiyor',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='randevu',
            name='durum',
            field=models.CharField(choices=[('BEKLEMEDE', 'Beklemede'), ('ONAYLANDI', 'Onaylandı'), ('TAMAMLANDI', 'Tamamlandı'), ('IPTAL_EDILDI', 'İptal Edildi')], db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='randevu',
            name='randevu_tarih_saat',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='randevu',
            name='tip',
            field=models.CharField(choices=[('ON_GORUSME', 'Ön Görüşme'), ('UCRETLI', 'Ücretli')], db_index=True, max_length=20),
        ),
        migrations.AddIndex(
            model_name='kullanici',
            index=models.Index(fields=['e_posta', 'aktif_mi'], name='idx_user_email_active'),
        ),
        migrations.AddIndex(
            model_name='kullanici',
            index=models.Index(fields=['rol', 'aktif_mi'], name='idx_user_role_active'),
        ),
        migrations.AddIndex(
            model_name='kullanici',
            index=models.Index(fields=['kayit_tarihi'], name='idx_user_created'),
        ),
        migrations.AddIndex(
            model_name='odemehareketi',
            index=models.Index(fields=['diyetisyen', 'odeme_tarihi'], name='idx_payment_dyt_date'),
        ),
        migrations.AddIndex(
            model_name='odemehareketi',
            index=models.Index(fields=['danisan', 'odeme_tarihi'], name='idx_payment_patient_date'),
        ),
        migrations.AddIndex(
            model_name='odemehareketi',
            index=models.Index(fields=['odeme_durumu', 'odeme_tarihi'], name='idx_payment_status_date'),
        ),
        migrations.AddIndex(
            model_name='randevu',
            index=models.Index(fields=['diyetisyen', 'randevu_tarih_saat'], name='idx_appointment_dyt_date'),
        ),
        migrations.AddIndex(
            model_name='randevu',
            index=models.Index(fields=['danisan', 'randevu_tarih_saat'], name='idx_appointment_patient_date'),
        ),
        migrations.AddIndex(
            model_name='randevu',
            index=models.Index(fields=['durum', 'randevu_tarih_saat'], name='idx_appointment_status_date'),
        ),
        migrations.AddIndex(
            model_name='randevu',
            index=models.Index(fields=['randevu_tarih_saat', 'durum'], name='idx_appointment_date_status'),
        ),
        migrations.AddIndex(
            model_name='randevu',
            index=models.Index(fields=['diyetisyen', 'durum'], name='idx_appointment_dyt_status'),
        ),
        migrations.AddConstraint(
            model_name='odemehareketi',
            constraint=models.CheckConstraint(check=models.Q(toplam_ucret__gte=0), name='check_positive_total_amount'),
        ),
        migrations.AddConstraint(
            model_name='odemehareketi',
            constraint=models.CheckConstraint(check=models.Q(komisyon_orani__gte=0, komisyon_orani__lte=100), name='check_commission_rate_valid'),
        ),
        migrations.AddConstraint(
            model_name='odemehareketi',
            constraint=models.CheckConstraint(check=models.Q(diyetisyen_kazanci__lte=models.F('toplam_ucret')), name='check_dietitian_earnings_valid'),
        ),
        migrations.AddConstraint(
            model_name='randevu',
            constraint=models.CheckConstraint(check=models.Q(randevu_tarih_saat__gte=datetime.datetime(2024, 1, 1, tzinfo=datetime.timezone.utc)), name='check_appointment_not_too_old'),
        ),
        migrations.AddConstraint(
            model_name='randevu',
            constraint=models.CheckConstraint(check=models.Q(models.Q(bitis_saati_gercek__isnull=True) | models.Q(bitis_saati_gercek__gte=models.F('baslangic_saati_gercek'))), name='check_end_time_after_start'),
        ),
    ]
