# Generated by Django 5.2.5 on 2025-10-14 13:42

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_kullanici_ad_alter_kullanici_aktif_mi_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MakaleKategori',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ad', models.CharField(db_index=True, max_length=100, unique=True)),
                ('aciklama', models.TextField(blank=True, null=True)),
                ('renk', models.CharField(default='#007bff', max_length=7)),
                ('sira', models.PositiveIntegerField(db_index=True, default=0)),
                ('aktif_mi', models.BooleanField(db_index=True, default=True)),
                ('olusturma_tarihi', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Makale Kategorisi',
                'verbose_name_plural': 'Makale Kategorileri',
                'db_table': 'makale_kategorileri',
                'ordering': ['sira', 'ad'],
            },
        ),
        migrations.AlterModelOptions(
            name='makale',
            options={'ordering': ['-yayimlanma_tarihi', '-olusturma_tarihi'], 'verbose_name': 'Makale', 'verbose_name_plural': 'Makaleler'},
        ),
        migrations.RemoveConstraint(
            model_name='randevu',
            name='check_appointment_not_too_old',
        ),
        migrations.AddField(
            model_name='makale',
            name='begeni_sayisi',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='makale',
            name='etiketler',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='makale',
            name='guncelleme_tarihi',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='makale',
            name='kapak_resmi',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='makale',
            name='okunma_sayisi',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='makale',
            name='olusturma_tarihi',
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='makale',
            name='onaylayan_admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='onayledigi_makaleler', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='makale',
            name='red_sebebi',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='makale',
            name='seo_aciklama',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='makale',
            name='seo_baslik',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='makale',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='makale',
            name='baslik',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='makale',
            name='onay_durumu',
            field=models.CharField(choices=[('BEKLEMEDE', 'Beklemede'), ('ONAYLANDI', 'Onaylandı'), ('REDDEDILDI', 'Reddedildi')], db_index=True, default='BEKLEMEDE', max_length=20),
        ),
        migrations.AlterField(
            model_name='makale',
            name='yayimlanma_tarihi',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='makale',
            name='yazar_kullanici',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='yazdigi_makaleler', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='randevu',
            constraint=models.CheckConstraint(check=models.Q(randevu_tarih_saat__gte=datetime.datetime(2024, 1, 1, tzinfo=datetime.timezone.utc)), name='check_appointment_not_too_old'),
        ),
        migrations.AddField(
            model_name='makale',
            name='kategori',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='makaleler', to='core.makalekategori'),
        ),
        migrations.AddIndex(
            model_name='makale',
            index=models.Index(fields=['onay_durumu', 'yayimlanma_tarihi'], name='idx_article_status_published'),
        ),
        migrations.AddIndex(
            model_name='makale',
            index=models.Index(fields=['kategori', 'onay_durumu'], name='idx_article_category_status'),
        ),
        migrations.AddIndex(
            model_name='makale',
            index=models.Index(fields=['yazar_kullanici', 'onay_durumu'], name='idx_article_author_status'),
        ),
        migrations.AddIndex(
            model_name='makale',
            index=models.Index(fields=['okunma_sayisi'], name='idx_article_views'),
        ),
    ]
