# Generated by Django 5.2.5 on 2025-10-14 14:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_add_article_categories_and_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bildirim',
            options={'ordering': ['-tarih'], 'verbose_name': 'Bildirim', 'verbose_name_plural': 'Bildirimler'},
        ),
        migrations.RemoveConstraint(
            model_name='randevu',
            name='check_appointment_not_too_old',
        ),
        migrations.AddField(
            model_name='bildirim',
            name='baslik',
            field=models.CharField(default='Bildirim', max_length=200),
        ),
        migrations.AddField(
            model_name='bildirim',
            name='gecerlilik_tarihi',
            field=models.DateTimeField(blank=True, help_text='Bu tarihten sonra bildirim gösterilmez', null=True),
        ),
        migrations.AddField(
            model_name='bildirim',
            name='hedef_url',
            field=models.CharField(blank=True, help_text='Bildirimi tıklandığında yönlendirilecek URL', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='bildirim',
            name='odeme_hareketi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.odemehareketi'),
        ),
        migrations.AddField(
            model_name='bildirim',
            name='oncelik',
            field=models.CharField(choices=[('DUSUK', 'Düşük'), ('NORMAL', 'Normal'), ('YUKSEK', 'Yüksek'), ('KRITIK', 'Kritik')], default='NORMAL', max_length=20),
        ),
        migrations.AddField(
            model_name='bildirim',
            name='randevu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.randevu'),
        ),
        migrations.AlterField(
            model_name='bildirim',
            name='alici_kullanici',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bildirimler', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bildirim',
            name='okundu_mu',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='bildirim',
            name='tarih',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='bildirim',
            name='tur',
            field=models.CharField(choices=[('RANDEVU_YENI', 'Yeni Randevu'), ('RANDEVU_ONAY', 'Randevu Onayı'), ('RANDEVU_IPTAL', 'Randevu İptali'), ('RANDEVU_HATIRLATMA', 'Randevu Hatırlatması'), ('ODEME_ONAY', 'Ödeme Onayı'), ('ODEME_HATA', 'Ödeme Hatası'), ('DIYET_HAZIR', 'Diyet Listesi Hazır'), ('DIYETISYEN_ONAY', 'Diyetisyen Onayı'), ('SISTEM_DUYURU', 'Sistem Duyurusu'), ('GENEL', 'Genel')], default='GENEL', max_length=50),
        ),
        migrations.AddIndex(
            model_name='bildirim',
            index=models.Index(fields=['alici_kullanici', '-tarih'], name='bildirimler_alici_k_6345bd_idx'),
        ),
        migrations.AddIndex(
            model_name='bildirim',
            index=models.Index(fields=['alici_kullanici', 'okundu_mu'], name='bildirimler_alici_k_f06679_idx'),
        ),
        migrations.AddIndex(
            model_name='bildirim',
            index=models.Index(fields=['tur', '-tarih'], name='bildirimler_tur_791d64_idx'),
        ),
    ]
