# Generated by Django 5.2.5 on 2025-10-14 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_bildirim_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diyetisyen',
            name='profil_fotografi_url',
        ),
        migrations.AddField(
            model_name='diyetisyen',
            name='profil_fotografi',
            field=models.ImageField(blank=True, null=True, upload_to='diyetisyen_profil/'),
        ),
    ]
