# Generated by Django 4.2.25 on 2025-10-15 06:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_diyetisyen_profil_fotografi_url_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='randevu',
            name='check_end_time_after_start',
        ),
        migrations.AddField(
            model_name='diyetisyen',
            name='onay_durumu',
            field=models.CharField(choices=[('BEKLEMEDE', 'Onay Bekliyor'), ('ONAYLANDI', 'Onaylandı'), ('REDDEDILDI', 'Reddedildi')], db_index=True, default='BEKLEMEDE', max_length=20),
        ),
        migrations.AddField(
            model_name='diyetisyen',
            name='onay_tarihi',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diyetisyen',
            name='onaylayan_admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='onayledigi_diyetisyenler', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='diyetisyen',
            name='red_nedeni',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='randevu',
            constraint=models.CheckConstraint(check=models.Q(('bitis_saati_gercek__isnull', True), ('bitis_saati_gercek__gte', models.F('baslangic_saati_gercek')), _connector='OR'), name='check_end_time_after_start'),
        ),
    ]
