# Generated by Django 5.2.5 on 2025-10-15 10:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_add_dietitian_approval'),
    ]

    operations = [
        migrations.AddField(
            model_name='randevu',
            name='randevu_turu',
            field=models.CharField(choices=[('ONLINE', 'Online Görüşme'), ('YUZEYUZ', 'Yüz Yüze Görüşme')], db_index=True, default='ONLINE', max_length=20),
        ),
        migrations.CreateModel(
            name='APIMetricsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('endpoint', models.CharField(db_index=True, max_length=255)),
                ('method', models.CharField(max_length=10)),
                ('status_code', models.IntegerField()),
                ('response_time', models.FloatField()),
                ('user_role', models.CharField(blank=True, max_length=50)),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'api_metrics',
                'indexes': [models.Index(fields=['timestamp', 'endpoint'], name='api_metrics_timesta_061d07_idx'), models.Index(fields=['status_code', 'timestamp'], name='api_metrics_status__6f6d5a_idx'), models.Index(fields=['user_role', 'timestamp'], name='api_metrics_user_ro_f2418c_idx')],
            },
        ),
    ]
