# Generated by Django 5.2.5 on 2025-10-15 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_add_randevu_turu_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='randevu',
            name='randevu_turu',
            field=models.CharField(choices=[('ONLINE', 'Online Görüşme')], db_index=True, default='ONLINE', max_length=20),
        ),
    ]
